name = 'alt:V Server'
port = 7788
players = 5
announce = false
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['js-module-v2']
debug = true
resources = [
  'core',
  'example'
]
